### ISSUE TITLE
feature request: power control

### ISSUE THREAD

**Issue by dev-zero** [tv42/bella#1]
I just stumbled over your little project here and since I submitted a couple of PRs to dymoprint it is nice to see a project which reuses the CUPS facilities instead.

So, if you're going to implement a webinterface (which would be awesome, btw), it would be nice to have automated USB power control (e.g. turn off after some idle time, turn on before using). The use case is to attach the LabelManager either to a router or an RPi already doing other things and not wanting to have it on all the time. I know, this would mean going around CUPS again and since there's a big button on the device I'd understand if you'd consider this an anti feature.

**Comment by tv42** [comment]
How would that actually happen? My Dymo (or the Linux driver) doesn't seem to support USB power control, `echo auto >/sys/devices/pci0000:00/0000:00:1a.0/usb1/1-1/1-1.1/power/control` does nothing.

If you're asking for some hooks that run arbitrary things to remote control some e.g. USB hub, I'm not inclined to adding a general hook mechanism. You can always wrap your call to bella with power-on/power-off calls.

You could also do that with CUPS. The simplest thing would be just to monitor the queue size, and whenever >0, send remote control command "on". When ==0 for 5 minutes, send remote control command "off".

**Comment by tv42** [comment]
Please give me more information about your use case. As of now, I don't see how it'd fit well into this piece of software.
