### ISSUE TITLE
feature request: QR code

### ISSUE THREAD

**Issue by dev-zero** [tv42/bella#2]
You've it already on the todo list, but what I saw from messing with the QR print thing on dymoprint is that given the limited resolution one has to be careful on how much information you can put in a QR code and still have it recognizable.
So, automated analysis (including error correction tuning) might be very interesting, besides exact control over dithering and placement.

**Comment by tv42** [comment]
Typical QR codes are 21-40 pixels tall. We have 64 vertical pixels to play with. For many QR codes, we can even 2x resize it for scannability. Testing whether a 40-pixel QR code printed 1:1 by a Dymo is scannable by a phone would be a good exercise.

The way to encode more data in limited vertical space is to have multiple 2D bar codes in a row. Of course, reader support gets trickier, but e.g. an Amazon box that just arrived here has a row of 3 (non-QR) 2D bar codes on it. (QR specifically gets confused by multiple codes nearby, so either a non-QR code or scanner support is going to be needed.)

I don't see a bug/issue here, and I don't want tickets open for things that might get done later and that are in the README already, so closing.
